/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u         /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PCR_PE_pe1 0x01u           /*!<@brief Pull Enable: Enables */
#define PCR_PS_ps1 0x01u           /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT2_PCR0_MUX_mux10 0x02u /*!<@brief Pin Multiplex Control: Alternative 2 (chip-specific) */
#define PORT2_PCR1_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT3_14 (number 28), Led
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Led_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Led_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Led_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Led_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Led_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Led_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Led_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_1 (number 11), LCD_BL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_BL_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_BL_INIT_GPIO_VALUE 1U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LCD_BL_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_BL_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_BL_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_BL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_BL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT1_3 (number 48), LCD_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_CS_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_CS_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_CS_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_CS_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_CS_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_CS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_10 (number 32), LCD_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCD_DC_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LCD_DC_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LCD_DC_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCD_DC_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCD_DC_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT2_2 (number 12), PushButton
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PushButton_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PushButton_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_PushButton_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PushButton_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PushButton_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PushButton_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
