/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA154
package_id: MCXA154VFT
mcu_data: ksdk2_0
processor_version: 25.06.10
pin_labels:
- {pin_num: '28', pin_signal: P3_14/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/FLEXIO0_D22/PWM1_A1, label: Led, identifier: Led}
- {pin_num: '11', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9, label: LCD_BL, identifier: LCD_BL}
- {pin_num: '48', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11, label: LCD_CS, identifier: LCD_CS}
- {pin_num: '32', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/FLEXIO0_D18, label: LCD_DC, identifier: LCD_DC}
- {pin_num: '33', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/FLEXIO0_D17, label: LCD_RST, identifier: LCD_RST}
- {pin_num: '12', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10, label: PushButton, identifier: PushButton}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: SCG0, signal: XTAL, pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/FLEXIO0_D30}
  - {pin_num: '7', peripheral: SCG0, signal: EXTAL, pin_signal: P1_31/TRIG_IN4/LPI2C0_SCL/CT_INP17/FLEXIO0_D31}
  - {pin_num: '10', peripheral: LPUART0, signal: RX, pin_signal: P2_0/TRIG_IN6/LPUART0_RXD/LPUART4_CTS_B/CT_INP16/CT2_MAT0/FLEXIO0_D8}
  - {pin_num: '41', peripheral: LPUART0, signal: TX, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/FLEXIO0_D3/CMP0_OUT}
  - {pin_num: '28', peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: P3_14/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/FLEXIO0_D22/PWM1_A1, direction: OUTPUT}
  - {pin_num: '28', peripheral: WUU0, signal: 'P, 25', pin_signal: P3_14/LPUART2_RXD/LPUART3_CTS_B/CT_INP6/PWM0_X2/FLEXIO0_D22/PWM1_A1, identifier: ''}
  - {pin_num: '11', peripheral: GPIO2, signal: 'GPIO, 1', pin_signal: P2_1/TRIG_IN7/LPUART0_TXD/LPUART4_RTS_B/CT_INP17/CT2_MAT1/FLEXIO0_D9, direction: OUTPUT, gpio_init_state: 'true',
    pull_select: up, pull_enable: enable}
  - {pin_num: '48', peripheral: GPIO1, signal: 'GPIO, 3', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11}
  - {pin_num: '48', peripheral: WUU0, signal: 'P, 7', pin_signal: P1_3/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11, identifier: ''}
  - {pin_num: '32', peripheral: GPIO3, signal: 'GPIO, 10', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2/FLEXIO0_D18}
  - {pin_num: '33', peripheral: GPIO3, signal: 'GPIO, 9', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/FLEXIO0_D17, identifier: ''}
  - {pin_num: '46', peripheral: LPSPI0, signal: SCK, pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/FLEXIO0_D9}
  - {pin_num: '45', peripheral: LPSPI0, signal: OUT, pin_signal: P1_0/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/FLEXIO0_D8}
  - {pin_num: '43', peripheral: LPI2C0, signal: SDA, pin_signal: P0_16/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/FLEXIO0_D0}
  - {pin_num: '44', peripheral: LPI2C0, signal: SCL, pin_signal: P0_17/LPI2C0_SCL/LPSPI0_PCS3/CT0_MAT1/UTICK_CAP3/FLEXIO0_D1}
  - {pin_num: '12', peripheral: GPIO2, signal: 'GPIO, 2', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* LPI2C0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* LPSPI0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t LCD_BL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_1 (pin 11)  */
    GPIO_PinInit(BOARD_INITPINS_LCD_BL_GPIO, BOARD_INITPINS_LCD_BL_PIN, &LCD_BL_config);

    gpio_pin_config_t PushButton_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_2 (pin 12)  */
    GPIO_PinInit(BOARD_INITPINS_PushButton_GPIO, BOARD_INITPINS_PushButton_PIN, &PushButton_config);

    gpio_pin_config_t Led_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin 28)  */
    GPIO_PinInit(BOARD_INITPINS_Led_GPIO, BOARD_INITPINS_Led_PIN, &Led_config);

    /* Interrupt configuration on GPIO2_2 (pin 12): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_PushButton_GPIO, BOARD_INITPINS_PushButton_PIN, kGPIO_InterruptRisingEdge);

    /* PORT0_16 (pin 43) is configured as LPI2C0_SDA */
    PORT_SetPinMux(PORT0, 16U, kPORT_MuxAlt2);

    PORT0->PCR[16] = ((PORT0->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_17 (pin 44) is configured as LPI2C0_SCL */
    PORT_SetPinMux(PORT0, 17U, kPORT_MuxAlt2);

    PORT0->PCR[17] = ((PORT0->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_3 (pin 41) is configured as LPUART0_TXD */
    PORT_SetPinMux(PORT0, 3U, kPORT_MuxAlt2);

    PORT0->PCR[3] = ((PORT0->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_0 (pin 45) is configured as LPSPI0_SDO */
    PORT_SetPinMux(PORT1, 0U, kPORT_MuxAlt2);

    PORT1->PCR[0] = ((PORT1->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_1 (pin 46) is configured as LPSPI0_SCK */
    PORT_SetPinMux(PORT1, 1U, kPORT_MuxAlt2);

    PORT1->PCR[1] = ((PORT1->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_3 (pin 48) is configured as P1_3, WUU0_IN7 */
    PORT_SetPinMux(BOARD_INITPINS_LCD_CS_PORT, BOARD_INITPINS_LCD_CS_PIN, kPORT_MuxAlt0);

    PORT1->PCR[3] = ((PORT1->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_30 (pin 6) is configured as XTAL48M */
    PORT_SetPinMux(PORT1, 30U, kPORT_MuxAlt0);

    PORT1->PCR[30] = ((PORT1->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_31 (pin 7) is configured as EXTAL48M */
    PORT_SetPinMux(PORT1, 31U, kPORT_MuxAlt0);

    PORT1->PCR[31] = ((PORT1->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[0] = ((PORT2->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_0 (pin 10) is configured as LPUART0_RXD. */
                     | PORT_PCR_MUX(PORT2_PCR0_MUX_mux10)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[1] = ((PORT2->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pull Select: Enables internal pullup resistor. */
                     | PORT_PCR_PS(PCR_PS_ps1)

                     /* Pull Enable: Enables. */
                     | PORT_PCR_PE(PCR_PE_pe1)

                     /* Pin Multiplex Control: PORT2_1 (pin 11) is configured as P2_1. */
                     | PORT_PCR_MUX(PORT2_PCR1_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 12) is configured as P2_2. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_10 (pin 32) is configured as P3_10 */
    PORT_SetPinMux(BOARD_INITPINS_LCD_DC_PORT, BOARD_INITPINS_LCD_DC_PIN, kPORT_MuxAlt0);

    PORT3->PCR[10] = ((PORT3->PCR[10] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_14 (pin 28) is configured as P3_14, WUU0_IN25 */
    PORT_SetPinMux(BOARD_INITPINS_Led_PORT, BOARD_INITPINS_Led_PIN, kPORT_MuxAlt0);

    PORT3->PCR[14] = ((PORT3->PCR[14] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_9 (pin 33) is configured as P3_9 */
    PORT_SetPinMux(PORT3, 9U, kPORT_MuxAlt0);

    PORT3->PCR[9] = ((PORT3->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
